spring:
  application:
    name: localization-be
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      write-enums-using-to-string: true
    deserialization:
      read-enums-using-to-string: true
      fail-on-unknown-properties: false
  data:
    mongodb:
      uuid-representation: standard
      auto-index-creation: false
      uri: ${MONGO_PREFIX:mongodb}://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:localization}
