name: github-action-pr
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.1
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Build
        run: ./gradlew build
      - name: Check code coverage
        uses: codecov/codecov-action@v2
      - name: Snyk monitor
        run: snyk test --severity-threshold=high --sarif-file-output=snyk.sarif
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload Snyk result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

