name: github-action-merge
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: localization-be

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Semver
        id: semver
        uses: codacy/git-version@2.2.0
        with:
          release-branch: main
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.1
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Build
        run: ./gradlew build
      - name: Check code coverage
        uses: codecov/codecov-action@v2
      - name: Snyk monitor
        run: snyk test --severity-threshold=high --sarif-file-output=snyk.sarif
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload Snyk result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.VERSION }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.VERSION }}
          release_name: v${{ steps.semver.outputs.VERSION }}
          draft: false
          prerelease: false
